brandleadership/stadler-prototype

src/app/lieferanten/page.tsx, src/components/sections/Quote.tsx
- Add quote section suggestion
=> feat: Add quote section

src/app/unternehmen/konzernleitung/page.tsx, src/app/unternehmen/verwaltungsrat/page.tsx, src/components/HomePageCaroucel.tsx, src/components/ReferenzenCarousel.tsx, src/components/typography/H1.tsx, src/components/typography/H2.tsx, src/components/typography/H3.tsx, src/components/typography/H4.tsx, src/components/typography/Lead.tsx, src/components/typography/Text.tsx
add images to the sections
adjusted spacings in typography
=> Typography

src/components/Stats.tsx, src/components/sections/FactsAndFigures.tsx
add animation
fix colors
add content
fix stats on scroll
=> Facts figures fix

src/components/layouts/ContentWidth.tsx, src/components/layouts/FullWidth.tsx, src/components/sections/FactsAndFigures.tsx, src/components/sections/HomePageCaroucel.tsx, src/components/sections/Video.tsx
=> feat: Add responsiveness for large screens

src/app/[lang]/[...slug]/page.js, src/app/[lang]/not-found.js, src/app/[lang]/page.js
=> add not found page

src/components/sections/Testimonials.js
=> fix testimonials

src/components/StoryblokProvider.js, src/components/sections/SocialWallComponent.js
Implemented:
- social wall compinent using iframe from juicer.io
=> feat: social wall

src/components/sections/ArticleHero.js, src/components/sections/DownloadElementLanguage.js, src/components/sections/HeroCareer.js, src/components/sections/HeroText.js, src/components/sections/MedienmitteilungenTeaser.js, src/components/sections/ProspectiveCareer.js, src/components/sections/Quote.js
Fixed mobile view of components
=> fix: mobile view

src/components/sections/ReferenzenCarousel.js
Fix slider visibility on mobile
=> fix: slider visibility

src/components/sections/AlleMedienmitteilungen.js, src/components/sections/MedienmitteilungenTeaser.js
Fixed: Media table view, filter logic
=> fix: media release row, filter logic

src/components/sections/HeaderNew.js, src/components/sections/TrainSequence.js
=> fix: header

src/app/[lang]/api/docs/route.js, src/components/helpers/ButtonUrlRenderer.js
=> add: link url rewritting

src/app/[lang]/api/docs/route.js
=> remove log

src/components/sections/AccordionTextDateDownloadItem.js, src/components/sections/MedienmitteilungDownloadLink.js
=> fix: links

src/components/sections/AlleMedienmitteilungen.js, src/components/sections/MedienmitteilungDownloadLink.js, src/components/sections/MedienmitteilungenTeaser.js, src/components/sections/SchienenfahrzeugeGrid.js
=> fix: target blank

src/components/sections/ReferenzContent.js
=> fix: tags position

src/components/sections/Layout.js
=> fix: sticky footer

src/components/sections/AccordionTextDateDownloadItem.js, src/components/sections/AccordionYearWrapper.js
=> fix: tables view

next.config.js, src/app/[lang]/layout.js, src/components/sections/ReportsItem.js.js, src/components/sections/SocialWallComponent.js, src/components/sections/TrainSequence.js
Fixed: download links, iframe, train slider
=> fix: download links, iframe, train slider

src/app/[lang]/layout.js, src/components/helpers/ButtonUrlRenderer.js
=> remove: src

src/components/sections/VideoFullWidth.js
=> fix: video autoplay

src/components/sections/Intro.js
=> fix: intro

src/components/sections/DownloadSecondaryGrid.js, src/components/sections/DownloadSecondaryItem.js
fix: download item mobile view
=> fix: download item

next.config.js
=> feat: redirects

next.config.js
=> fix: de karrieere url

src/components/elements/LanguageSwitcher.js
=> fix: language switcher

src/components/sections/SocialWallComponent.js
Implemented: 3 posts ion social wall with 'Load more' button
=> feat: 3 posts on social wall

src/app/[lang]/page.js, src/components/sections/SocialWallComponent.js
Implemented: 3 posts on social wall with "Load more" button
=> Next no typescript

src/components/sections/SocialWallComponent.js
=> fix: less gap

src/app/[lang]/[...slug]/page.js, src/app/[lang]/page.js, src/components/sections/Page.js
Reverts brandleadership/stadler-prototype#541
=> Revert "feature: preview for new pages"
